#!/bin/bash

CALLING_DIR=$(pwd)

function help {
	echo "Remote Environment client."
	echo
	echo "Usage:"
	echo "  ${0} command"
	echo 
	echo "Available commands:"
	echo "   setup             Setup the remote environment client and settings"
	echo "   build             Create/Update the remote environment"
	echo "   watch             Watch local changes and synchronize with the remote environment"
	echo "   ssh               SSH into the remote environment container"
	echo "   resync            Sync remote changes to and from the local filesystem"
	echo "   destroy           Destroy the remote environment"
}

function container_specified {
   if [ -z "$1" ]; then
       echo "You need to specify the container to use with this command"
       exit;
   fi
}

command_exists () {
    type "$1" &> /dev/null ;
}

function dir {
    echo "$CALLING_DIR"
}

function settings_file {
    echo "$(dir)/.remote"
}

function project_key {
    read_setting 4
}

function remote_name {
    read_setting 3
}

function remote_branch {
    read_setting 2
}

function namespace {
    read_setting 1
}

function keen_write_key {
    read_setting 5
}

function keen_project_id {
    read_setting 6
}

function keen_event_collection {
    read_setting 7
}

function pod {
    CONTAINER=$1
    kubectl --context="$(namespace)" --namespace="$(namespace)" get pods | grep "$CONTAINER" | awk '{print $1}'
}

function pod_found {
    if [ -z "$1" ]; then
        echo
        echo "The pod could not be found, is your configuration correct and is the specified container name correct?"
        echo
        exit;
    fi
}

function local_branch {
    git rev-parse --abbrev-ref HEAD
}

function read_setting {
    sed "$1q;d" "$(dir)/.remote"
}

function validate_settings {
    NUMBER_OF_REQUIRED_SETTINGS=4

    if [ ! -f "$(settings_file)" ]; then
         echo "The remote settings file is missing, please run the setup command"
         exit;
    fi

    NUM_SETTINGS=$(wc -l "$(settings_file)" | awk '{print $1}')
    if [ "$NUM_SETTINGS" -lt "$NUMBER_OF_REQUIRED_SETTINGS" ]; then
         echo "The remote settings file does not have all the required settings, please run the setup command"
         exit;
    fi
}

function setup {
	if ! command_exists kubectl ; then
		echo "[INSTALL] kubectl is being installed"

		if [[ "$OSTYPE" == "darwin"* ]]; then
			curl -O https://storage.googleapis.com/kubernetes-release/release/v1.4.3/bin/darwin/amd64/kubectl
			chmod +x kubectl
			sudo mv kubectl /usr/local/bin/kubectl
		else
			curl -O https://storage.googleapis.com/kubernetes-release/release/v1.4.3/bin/linux/amd64/kubectl
			chmod +x kubectl
			sudo mv kubectl /usr/bin/kubectl
		fi
	else
		echo "[OK] kubectl found"
	fi
	
	REMOTE_DIR="$(dir)/.remote"
    
    read -r -p "What is your project key? " PROJECT_KEY
    read -r -p "What is your remote development namespace? " NAMESPACE
    read -r -p "What is the name of the Git branch you are using for your remote environment? " REMOTE_BRANCH
    read -r -p "What is your github remote name? (origin) " REMOTE_NAME
    read -r -p "What is the IP of the cluster? " CLUSTER_IP
    read -r -p "What is the username? " USERNAME
    read -r -p "What is the password? " PASSWORD
    read -r -p "What is your keen.io write key? (Optional, only needed if you want to record usage stats) " KEEN_WRITE_KEY
    read -r -p "What is your keen.io project id? (Optional, only needed if you want to record usage stats) " KEEN_PROJECT_ID
    read -r -p "What is your keen.io event collection?  (Optional, only needed if you want to record usage stats) " KEEN_EVENT_COLLECTION

    REMOTE_NAME="${REMOTE_NAME:-origin}"
    echo "$NAMESPACE" > "$REMOTE_DIR"
    echo "$REMOTE_BRANCH" >> "$REMOTE_DIR"
    echo "$REMOTE_NAME" >> "$REMOTE_DIR"
    echo "$PROJECT_KEY" >> "$REMOTE_DIR"
    echo "$KEEN_WRITE_KEY" >> "$REMOTE_DIR"
    echo "$KEEN_PROJECT_ID" >> "$REMOTE_DIR"
    echo "$KEEN_EVENT_COLLECTION" >> "$REMOTE_DIR"
    echo "Remote settings written to $REMOTE_DIR"

    kubectl config set-credentials "$NAMESPACE-$USERNAME" --username="$USERNAME" --password="$PASSWORD"
    kubectl config set-cluster "$NAMESPACE" --server="https://$CLUSTER_IP" --insecure-skip-tls-verify=true
    kubectl config set-context "$NAMESPACE" --cluster="$NAMESPACE" --user="$NAMESPACE-$USERNAME"

    echo "Created the context " "$NAMESPACE"
    echo
    echo "Run 'kubectl --context=$(namespace) cluster-info' to verify the connectivity."
    echo
}

function log {
    PROJECT_ID="$(keen_project_id)"
    WRITE_KEY="$(keen_write_key)"
    EVENT_COLLECTION="$(keen_event_collection)"

    if [ -z "$PROJECT_ID" ] || [ -z "$WRITE_KEY" ] || [ -z "$EVENT_COLLECTION" ]; then
    	echo "Not logging usage stats as keen.io details not set"
    	exit 0
    else
    	echo "Logging usage stats to keen.io"
    fi

    END_TIME="$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
    PAYLOAD='{"project": "'"$(project_key)"'" ,"namespace": "'"$(namespace)"'","command": "'"$1"'","start-time": '$2',"end-time": '$END_TIME'}'
    curl -s "https://api.keen.io/3.0/projects/$PROJECT_ID/events/$EVENT_COLLECTION?api_key=$WRITE_KEY" -H "Content-Type: application/json" -d "$PAYLOAD" >/dev/null
}

function build {
    START_TIME="$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
    ensure_new_commit
    push_to_remote
    log "build" "$START_TIME"
}

function ensure_new_commit {
    git ls-remote --exit-code --quiet  . "$(remote_name)/$(remote_branch)"
    rc=$?; if [[ $rc != 0 ]]; then
        return
    fi

    git diff --exit-code --quiet "$(local_branch)" "$(remote_name)/$(remote_branch)"
    rc=$?; if [[ $rc = 0 ]]; then
        echo "No changes so making timestamp update only commit to force rebuild";
        date +%s > "$(dir)/timestamp"
        git commit "$(dir)/timestamp" -m "Update timestamp to force rebuild on continuous pipe"
    fi
}

function push_to_remote {
    echo "Pushing to remote"
    git push --force "$(remote_name)" "$(local_branch):$(remote_branch)"

    echo "Continuous Pipe will now build your developer environment"
}

function delete_remote {
    echo "Destroying remote environment"
    echo "Deleting remote branch"
    git push "$(remote_name)" --delete "$(remote_branch)"

    echo "Continuous Pipe will now destroy the remote environment"
}

function ssh {
    POD="$(pod "$1")"
    pod_found "$POD"
    cmd="kubectl --context=\"$(namespace)\" --namespace=\"$(namespace)\" exec -it $POD -- /bin/bash"
    echo "Running: '${cmd}'."
    eval "${cmd}"
}

function watch {
    # Sync latency / speed in seconds
    LATENCY="1"
    PROJECT_DIR_WITH_DOT="$(dir)/."
    POD="$(pod "$1")"
    pod_found "$POD"

    echo "The watch command will need to be restarted after rebuilding the remote environment"
    # Watch for changes and sync (exclude hidden files)
    echo    "Watching for changes. Quit anytime with Ctrl-C."
    fswatch -0 -r -l "$LATENCY" .. --exclude="/\.[^/]*$" --exclude="\.idea" --exclude="\.git" --exclude="___jb_old___" --exclude="___jb_tmp___" \
    | while read -r -d "" event
      do
        echo "$(date)" "\"$event\" changed. Synchronizing... "
        file="${event/$(dir)/$PROJECT_DIR_WITH_DOT}"
        echo

        rsync --relative -rlptDv -e 'kubectl --context='"$(namespace)"' --namespace='"$(namespace)"' exec -i '"$POD" -- "$file" --:/app
        echo "done."
      done
}

function resync {
    START_TIME="$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
    POD=$(pod "$1")
    pod_found "$POD"

    git stash save -q --keep-index

    rc=$?; if [[ $rc != 0 ]]; then
        echo "Stashing your existing local changes failed so the resync was cancelled."
        exit
    fi

    rsync -zrlptDv --blocking-io  --force --exclude=".*" \
        -e 'kubectl --context='"$(namespace)"' --namespace='"$(namespace)"' exec -i '"$POD" -- --:/app/ "$(dir)"

    git reset --hard -q && git stash apply --index -q && git stash drop -q

    rsync -zrlptDv --blocking-io  --force --exclude=".*" \
        -e 'kubectl  --context='"$(namespace)"' --namespace='"$(namespace)"' exec -i '"$POD" -- "$(dir)/." --:/app

    log "resync" "$START_TIME"
}

case $1 in
    -h|--help|help)
    help
    exit 0
    ;;
    setup|build|watch|ssh|destroy|resync)
    COMMAND="$1"
    ;;
    *)
        echo "Unknown option: $1"
    ;;
esac

if [ -z "${COMMAND+x}" ]; then
	help
	exit 0
fi

case $COMMAND in
	setup)
		setup
		;;
    watch)
        container_specified "$2"
        validate_settings
        watch "$2"
        ;;
    build)
        validate_settings
        build
        ;;
    ssh)
        container_specified "$2"
        validate_settings
        ssh "$2"
        ;;
    destroy)
        validate_settings
        delete_remote
        ;;
    resync)
        container_specified "$2"
        validate_settings
        resync "$2"
        ;;
	*)
		echo "Command not found: $COMMAND"
		echo
		help
		exit 1
		;;
esac
