[[constraint]]
  name = "github.com/fatih/color"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/sanbornm/go-selfupdate"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "~1.1.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.6.0-alpha.0"

[prune]
  go-tests = true
  unused-packages = true
